spring.datasource.url=jdbc:postgresql://localhost:5432/expense_db
spring.datasource.username=expuser
spring.datasource.password=exp_pass_123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
